# -*- coding: utf-8 -*-
"""
Created on Sat May 26 14:33:00 2018

@author: SFAdr
"""

#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 23, 2018 10:53:30 PM

import sys
import InsertQuries as iq


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import TicketTable_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    TicketTable_support.set_Tk_var()
    top = New_Toplevel (root)
    TicketTable_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    TicketTable_support.set_Tk_var()
    top = New_Toplevel (w)
    TicketTable_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 12 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
            
        addressI = StringVar()
        cnicI = StringVar()
        empidI = StringVar()
        salaryI = StringVar()
        nameI = StringVar()
        jobI = StringVar()
        
        addressU = StringVar()
        nameU = StringVar()
        customeridU  = StringVar()
        salaryU = StringVar()
        jobU = StringVar()
        theateridU = StringVar()
        
        delete = StringVar()
        
        

        top.geometry("1920x1001+-1+2")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=-0.01, rely=-0.06, relheight=1.09, relwidth=1.06)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#161668")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=2035)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.14, rely=0.21, height=26, width=112)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#161668")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''ID''')
        
#ID,Name,CNIC,Salary,Job,Address
        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.15, rely=0.31, height=26, width=82)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#161668")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name''')

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.3, rely=0.21, height=26, width=62)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#161668")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''CNIC''')

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.45, rely=0.21, height=26, width=112)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#161668")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Salary''')

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.29, rely=0.32, height=26, width=82)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#161668")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Job''')

        self.Entry1 = Entry(self.Frame1)
        self.Entry1.place(relx=0.37, rely=0.31,height=34, relwidth=0.05)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        
        self.Entry1.configure(textvariable = jobI)


        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.21, rely=0.2,height=34, relwidth=0.05)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable = empidI)

        self.Entry3 = Entry(self.Frame1)
        self.Entry3.place(relx=0.21, rely=0.31,height=34, relwidth=0.05)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")        
        self.Entry3.configure(textvariable = nameI)


        self.Entry4 = Entry(self.Frame1)
        self.Entry4.place(relx=0.36, rely=0.21,height=34, relwidth=0.05)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")        
        self.Entry4.configure(textvariable = cnicI)


        self.Entry5 = Entry(self.Frame1)
        self.Entry5.place(relx=0.55, rely=0.2,height=34, relwidth=0.05)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        
        self.Entry5.configure(textvariable = salaryI)


        self.Label6 = Label(self.Frame1)
        self.Label6.place(relx=0.36, rely=0.1, height=26, width=332)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#161668")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font9)
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Enter data in Employee Table''')

        self.Label7 = Label(self.Frame1)
        self.Label7.place(relx=0.16, rely=0.46, height=26, width=61)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#161668")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Job''')

        self.Label8 = Label(self.Frame1)
        self.Label8.place(relx=0.43, rely=0.58, height=26, width=192)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#161668")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#ffffff")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Where    Employee ID    =''')

        self.Label9 = Label(self.Frame1)
        self.Label9.place(relx=0.29, rely=0.57, height=26, width=112)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#161668")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#ffffff")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Salary''')

        self.Label10 = Label(self.Frame1)
        self.Label10.place(relx=0.29, rely=0.46, height=26, width=75)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#161668")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#ffffff")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''CNIC''')

        self.Label11 = Label(self.Frame1)
        self.Label11.place(relx=0.15, rely=0.57, height=26, width=66)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#161668")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#ffffff")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Name''')

        self.Label12 = Label(self.Frame1)
        self.Label12.place(relx=0.37, rely=0.37, height=26, width=302)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#161668")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(font=font9)
        self.Label12.configure(foreground="#ffffff")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''Update data in Employee Table''')

        self.Entry6 = Entry(self.Frame1)
        self.Entry6.place(relx=0.55, rely=0.57,height=34, relwidth=0.05)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(textvariable = customeridU)

        self.Entry7 = Entry(self.Frame1)
        self.Entry7.place(relx=0.36, rely=0.57,height=34, relwidth=0.05)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(textvariable = salaryU)
        

        self.Entry8 = Entry(self.Frame1)
        self.Entry8.place(relx=0.36, rely=0.45,height=34, relwidth=0.05)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")
        self.Entry8.configure(textvariable = theateridU)
        

        self.Entry9 = Entry(self.Frame1)
        self.Entry9.place(relx=0.21, rely=0.56,height=34, relwidth=0.05)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(highlightbackground="#d9d9d9")
        self.Entry9.configure(highlightcolor="black")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(selectforeground="black")
        self.Entry9.configure(textvariable = nameU)
        


        self.Entry10 = Entry(self.Frame1)
        self.Entry10.place(relx=0.21, rely=0.45,height=34, relwidth=0.05)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(highlightbackground="#d9d9d9")
        self.Entry10.configure(highlightcolor="black")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(selectforeground="black")
        self.Entry10.configure(textvariable = jobU)

        self.Label13 = Label(self.Frame1)
        self.Label13.place(relx=0.38, rely=0.66, height=26, width=322)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#161668")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font=font9)
        self.Label13.configure(foreground="#ffffff")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''Delete data from Employee Table''')

        self.Entry11 = Entry(self.Frame1)
        self.Entry11.place(relx=0.5, rely=0.78,height=34, relwidth=0.05)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")
        self.Entry11.configure(textvariable = delete)

        self.Label14 = Label(self.Frame1)
        self.Label14.place(relx=0.23, rely=0.78, height=26, width=42)
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#161668")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#ffffff")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''From''')

        self.Label15 = Label(self.Frame1)
        self.Label15.place(relx=0.32, rely=0.78, height=26, width=42)
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(background="#161668")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#ffffff")
        self.Label15.configure(highlightbackground="#d9d9d9")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''Where''')

        self.Label16 = Label(self.Frame1)
        self.Label16.place(relx=0.45, rely=0.78, height=26, width=42)
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(background="#161668")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#ffffff")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''=''')

        self.Label17 = Label(self.Frame1)
        self.Label17.place(relx=0.38, rely=0.78, height=26, width=92)
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(background="#161668")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#ffffff")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''Employee ID''')

        self.Label18 = Label(self.Frame1)
        self.Label18.place(relx=0.28, rely=0.78, height=26, width=52)
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(background="#161668")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#ffffff")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text=''' Employee ''')

        def getInsertEmp():
            iq.InsertQuries.empColumnInsert(empidI , cnicI , salaryI , jobI , nameI ,addressI)
            return
        
        def updateEmp():
            print("in tick"+ " " + customeridU.get() , nameU.get() , salaryU.get() , theateridU.get() , jobU.get() ,addressU.get() )
            iq.InsertQuries.empUpdate(customeridU , nameU , salaryU , theateridU , jobU ,addressU)
                                       
        def deleteEmp():
            iq.InsertQuries.empDelete(delete)
        
        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.66, rely=0.31, height=33, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#5fd87f")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Insert''')
        self.Button1.configure(command = getInsertEmp)

        self.Button2 = Button(self.Frame1)
        self.Button2.place(relx=0.66, rely=0.56, height=33, width=96)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d8ca6c")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Update''')
        self.Button2.configure(command = updateEmp)

        self.Button3 = Button(self.Frame1)
        self.Button3.place(relx=0.66, rely=0.79, height=33, width=96)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d8691e")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Delete''')
        self.Button3.configure(command = deleteEmp)

        self.Label19 = Label(self.Frame1)
        self.Label19.place(relx=0.02, rely=0.05, height=184, width=184)
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(activeforeground="black")
        self.Label19.configure(background="#161668")
        self.Label19.configure(disabledforeground="#a3a3a3")
        self.Label19.configure(foreground="#000000")
        self.Label19.configure(highlightbackground="#d9d9d9")
        self.Label19.configure(highlightcolor="black")
        self._img1 = PhotoImage(file="../../apple-touch-icon.png")
        self.Label19.configure(image=self._img1)
        self.Label19.configure(text='''Label''')

        self.Insert_TicketId = Entry(self.Frame1)
        self.Insert_TicketId.place(relx=0.55, rely=0.3, height=34, relwidth=0.05)

        self.Insert_TicketId.configure(background="white")
        self.Insert_TicketId.configure(disabledforeground="#a3a3a3")
        self.Insert_TicketId.configure(font="TkFixedFont")
        self.Insert_TicketId.configure(foreground="#000000")
        self.Insert_TicketId.configure(insertbackground="black")
        self.Insert_TicketId.configure(textvariable= addressI)
        self.Insert_TicketId.configure(width=104)

        self.Label20 = Label(self.Frame1)
        self.Label20.place(relx=0.45, rely=0.31, height=26, width=102)
        self.Label20.configure(background="#161668")
        self.Label20.configure(disabledforeground="#a3a3a3")
        self.Label20.configure(foreground="#ffffff")
        self.Label20.configure(text='''Address''')
        self.Label20.configure(width=102)

        self.Label21 = Label(self.Frame1)
        self.Label21.place(relx=0.45, rely=0.46, height=26, width=64)
        self.Label21.configure(background="#161668")
        self.Label21.configure(disabledforeground="#a3a3a3")
        self.Label21.configure(foreground="#ffffff")
        self.Label21.configure(text='''Address''')

        self.Entry13 = Entry(self.Frame1)
        self.Entry13.place(relx=0.55, rely=0.46,height=34, relwidth=0.05)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(width=104)
        self.Entry13.configure(textvariable = addressU)






if __name__ == '__main__':
    vp_start_gui()


